---
- src: https://github.com/open-io/ansible-role-openio-users.git
  version: "19.10"
  name: users

- src: https://github.com/open-io/ansible-role-openio-repository.git
  version: "19.10"
  name: repository

- src: https://github.com/open-io/ansible-role-openio-gridinit.git
  version: "19.10"
  name: gridinit
...
